name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling the repo
        uses: actions/checkout@v2
      - name: say hi to linush
        run: echo "hi linush"
